# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HealTAC 2026
email:
description: >- # this means to ignore newlines until "baseurl:"
  9th Healthcare Text Analytics Conference
url: https://healtac2026.github.io/
baseurl: /
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  # name   : "HealTAC 2026"
  # avatar : "/assets/images/bio-photo.jpg"
  # bio    : "9th Healthcare Text Analytics Conference"
  links:
    # - label: "<strong style='color:#003865;'>TUTORIAL</strong><br><span style='color: black;'>Resources<br>"
    #   icon: "fas fa-laptop-code"
    #   url: https://knowlab.github.io/healtac2025_tutorial/
    # - label: "<strong style='color:#003865;'>BOOK OF ABSTRACTS</strong><br><span style='color:black;'>Download<br>"
    #   icon: "fas fa-file-pdf"
    #   url: https://drive.usercontent.google.com/u/0/uc?id=1oBAgnUsqvdGFpUPL8GAdw5XmnF7M2gUC&export=download
    #   download: "HealTAC2025_Book_of_Abstracts.pdf"
    # - label: "<strong style='color:#003865;'>ACCOMMODATION</strong><br><span style='color:black;'>Book now.<br>"
    #   icon: "fas fa-home"
    #   url: https://healtac2025.github.io/accommodation/
    # - label: "<strong style='color:#003865;'>REGISTRATION</strong><br><span style='color:black;'>Now open.<br>"
    #   icon: "far fa-comment"
    # url: https://healtac2025.github.io/registration/
    # - label: "<strong style='color:#003865;'>Key Dates</strong><br>– <span style='color: black;'><strong>Conference:</strong><br>June 16-18, 2025<br>– <span style='color: black;'><strong>Deadline for all contributions:</strong><br>April 4, 2025<br>– <span style='color: black;'><strong>Notification of acceptance:</strong><br> April 18, 2025</span><br>"
    #    icon: "far fa-calendar-alt"
    #    url: https://healtac2025.github.io/submissions/
    #  - label: "<strong style='color:#003865;'>Keynotes</strong><br>– <span style='color: black;'><strong>Jason Fries</strong> (Stanford Uni)<br>– <span style='color: black;'><strong>Alison O'Neil</strong> (Canon Medical)"
    #   icon: "far fa-calendar-alt"
    #   url: https://healtac2025.github.io/programme/
    - label: "<strong style='color:#003865;'>Registration</strong><br>Registration will open in <p> early January<br><br>" 
      icon: "far fa-comment"
      url: ""
       
    # - label: "<strong style='color:#003865;'>Previous HealTACs</strong><br>"
    #   icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-conference-series/
    # - label: "<span style='color: black;'>HealTAC-2024</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-2024/
    # - label: "<span style='color: black;'>HealTAC-2023</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-2023/
    # - label: "<span style='color: black;'>HealTAC-2022</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: https://healtac2022.github.io/
    # - label: "<span style='color: black;'>HealTAC-2021</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-2021/
    # - label: "<span style='color: black;'>HealTAC-2020</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-2020/
    # - label: "<span style='color: black;'>HealTAC-2019</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-2019/
    # - label: "<span style='color: black;'>HealTAC-2018</span>"
    #   # icon: "fas fa-fw fa-link"
    #   url: http://healtex.org/healtac-2018/
    # - label: |
    #     <strong style='color:#003865;'>Sponsors</strong><br><br>
    #     <div style="display: flex; flex-direction: column;">
    #       <img src="/assets/images/sponsors/HDR UK.jpg" alt="HDR UK" style="margin-bottom: 10px; max-width: 100px;"><br><br>
    #       <img src="/assets/images/sponsors/HealTex.jpeg" alt="HealTex" style="margin-bottom: 10px; max-width: 100px;"><br><br>
    #       <img src="/assets/images/sponsors/Frontiers.jpg" alt="Frontiers" style="margin-bottom: 10px; max-width: 100px;"><br><br>
    #       <img src="/assets/images/sponsors/University of Glasgow.png" alt="University of Glasgow" style="margin-bottom: 10px; max-width: 100px;"><br><br>
    #       <img src="/assets/images/sponsors/Research Data Scotland.png" alt="Research Data Scotland" style="margin-bottom: 10px; max-width: 100px;"><br><br>
    #       <img src="/assets/images/sponsors/NCRM.jpg" alt="NCRM" style="margin-bottom: 10px; max-width: 100px;"><br><br>
    #     </div>
    #     <br><br>
    #   icon: "fas fa-handshake"
    #   url: ""
    - label: |
        <strong style='color:#003865;'>Sponsors</strong>
      icon: "fas fa-handshake"
      url: ""
    - label: |
        <div style="display: flex; flex-direction: column;">
          <img src="/assets/images/sponsors/HealTex.jpeg" alt="HealTex" style="margin-bottom: 2.5px; max-width: 100px;">
        </div>
      icon: "<i class='fas fa-square' style='visibility: hidden;'></i>"
      url: "http://healtex.org/"
    - label: |
        <div style="display: flex; flex-direction: column;">
          <img src="/assets/images/sponsors/kcl-logo.svg" alt="King's College London" style="margin-bottom: 2.5px; max-width: 100px;">
        </div>
      icon: "<i class='fas fa-square' style='visibility: hidden;'></i>"
      url: "https://www.kcl.ac.uk/"
    - label: |
        <div style="display: flex; flex-direction: column;">
          <img src="/assets/images/sponsors/BSMS-Logo-Black.jpg" alt="Brighton and Sussex Medical School" style="margin-bottom: 2.5px; max-width: 100px;">
        </div>
      icon: "<i class='fas fa-square' style='visibility: hidden;'></i>"
      url: "https://www.bsms.ac.uk/"      
    - label: "<br><br><strong style='color:#003865;'>Previous HealTACs</strong><br>"
      icon: "fas fa-fw fa-link"
      url: http://healtex.org/healtac-conference-series/
footer:
  links:
    - label: "Twitter/X"
#      icon: "fab fa-fw fa-twitter-square"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/uk_healtex"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/healtac2026/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
